spring:
  application:
    name: financial

  datasource:
    url: jdbc:mysql://localhost:3306/keywi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

financial:
  api:
    url: https://finopenapi.ssafy.io/ssafy/api/v1
    api-key: fc1880ecc2444474a54db3592c898761

  user:
    user-id: qkqhzz120@naver.com
    user-key: 042dc87f-0817-4f61-b879-cc1b27d59e58
    user-name: qkqhzz120